model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: False
use_lags: True
dataset: custom(/home/shihongyue/.gluonts/datasets/nasdaq100_prices)  # 指向你整理好的数据
freq: B
context_length: 96
prediction_length: 24
lr: 1.e-3
init_skip: True
gradient_clip_val: 0.5
max_epochs: 10
num_batches_per_epoch: 128
batch_size: 64
num_samples: 16
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 8
use_validation_set: True
eval_every: 50
device: cuda:0
setup: forecasting
